### ISSUE TITLE
[Bug]: Multichart in same page only loads one

### ISSUE THREAD

**Issue by DanyDes** [apertureless/vue-chartjs#801]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

I've been working with the library and when I needed to show multiple charts it did't work. I was using the `4.0.4` version then downgraded it to the version `4.0.3` and worked perfectly.

I just wanted to report it.

### Reproduction

https://codesandbox.io/s/optimistic-hill-nc0h95?file=/src/App.vue

### chart.js version

3.7.1

### vue-chartjs version

4.0.4

**Comment by edwardsph** [comment]
Thank you for raising this. I just upgraded from 3.5.1 to 4.0.4 and had the same problem. I would never have guessed to downgrade to 4.0.3.

**Comment by thabarbados** [comment]
@DanyDes @edwardsph fixed in [4.0.5](https://github.com/apertureless/vue-chartjs/releases/tag/v4.0.5)
You can check [here](https://codesandbox.io/s/gracious-ptolemy-e3lku8)

**Comment by akhchan99** [comment]
https://codesandbox.io/s/elegant-bhaskara-fupfoi?file=/src/App.vue

once chart data are reactive, only the last chart in the same page will be updated, and first chart either not updating or won't be display at all

**Comment by akhchan99** [comment]
If make make the chart data reactive, then only the last chart will update and shown (with 4.0.5)

**Comment by tttaisgt** [comment]
@thabarbados 
it works perfectly in the first render, but when I change the data of one chart, the rest charts will disappear, like this:
<img width="1118" alt="image" src="https://user-images.githubusercontent.com/68092893/162560880-866872be-0b08-4d57-ae20-b574c891b15e.png">

**Comment by thabarbados** [comment]
@tttaisgt Can you repo this bug on the sandbox?

**Comment by tttaisgt** [comment]
@thabarbados 
I have no experience with the sandbox environment 😓 , I tried to reproduce it but the phenomenon of
> If you make the chart data reactive, then only the last chart will update and shown (with 4.0.5)
>
occurs
the sandbox URL: https://codesandbox.io/s/pedantic-tharp-moi7lj?file=/src/App.vue

In my case, the code is similar to the URL above, the phenomenon of chart disappearing occurs, please see the video:

https://user-images.githubusercontent.com/68092893/162584948-cbe4ea57-0c3c-41e9-a101-abfabab3cfc0.mov

**Comment by hoduyquang75** [comment]
@thabarbados 
Cc: @tttaisgt 
I have the same problem as above. 😢 😭

**Comment by thabarbados** [comment]
@akhchan99 @tttaisgt @hoduyquang75 I am trying to fix this bug. Until I do this, you can downgrade to version 4.0.3.

**Comment by ShacharMeir007** [comment]
@thabarbados I think I have a solution for this bug, at least it worked when I tested it. Is there a way for me to push my changes?

**Comment by thabarbados** [comment]
@ShacharMeir007 Sounds great! 
You can fork the project, make changes and create a [PR](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork). Or you can put your code on codesandbox and send the link here.

**Comment by thabarbados** [comment]
Fixed in release [4.0.6](https://github.com/apertureless/vue-chartjs/releases/tag/v4.0.6), except for using Vue 2 and chartjs-plugin-annotation simultaneously. 
Added a [paragraph](https://vue-chartjs.org/guide/#chartjs-plugin-annotation) about this to the documentation

**Comment by hdquangsgt** [comment]
@thabarbados 

Screen.Recording.2022-04-10.at.00.27.37.mov

> Fixed in release [4.0.6](https://github.com/apertureless/vue-chartjs/releases/tag/v4.0.6), except for using Vue 2 and chartjs-plugin-annotation simultaneously. Added a [paragraph](https://vue-chartjs.org/guide/#chartjs-plugin-annotation) about this to the docs

It has still yet seem fix [the issue (multi chart load)](https://github.com/apertureless/vue-chartjs/issues/801#issuecomment-1094091478)
I'm still see this issue.
Please check again.
